### PR TITLE
Retain original exception when parsing fails type conversion

### LINKED ISSUE #67: ParseOptionConversionException is not transporting the cause
I have the following problem: my CLI application has commands accepting an argument, which I provide a class, ClusterID having a constructor taking a String, for parsing and validating the argument. 

```
    @Arguments(required = true, description = "Cluster ID ...")
    public ClusterID cluster;
```

While this is working fine for the happy case, ClusterID's constructor would raise an exception with a proper message if something has failed.

I'd like to report that message to the user, but I get an `io.airlift.airline.ParseOptionConversionException` only, without the cause.

```
io.airlift.airline.ParseOptionConversionException: cluster: can not convert "098" to a ClusterID
	at io.airlift.airline.TypeConverter.convert(TypeConverter.java:78)
	at io.airlift.airline.Parser.parseArg(Parser.java:265)
	at io.airlift.airline.Parser.parseArgs(Parser.java:255)
	at io.airlift.airline.Parser.parse(Parser.java:70)
	at io.airlift.airline.Cli.parse(Cli.java:121)
	at io.airlift.airline.Cli.parse(Cli.java:108)
	at io.airlift.airline.Cli.parse(Cli.java:103)
	at Main.main(Main.java:53)
```

I'd appreciate [TypeConverter.java#L75](https://github.com/airlift/airline/blob/fc7a55e34b6361cb97235de5a1b21cba9b508f4b/src/main/java/io/airlift/airline/TypeConverter.java#L75) would not ignore the Throwable but pass in on `io.airlift.airline.ParseOptionConversionException` as cause.

### PR DESCRIPTION
**Pull request by rtib**
Fixes #67

### CODE REVIEW

File: src/main/java/io/airlift/airline/TypeConverter.java [hunk 1]
```diff
@@ -72,7 +73,10 @@ else if (Double.class.isAssignableFrom(type) || Double.TYPE.isAssignableFrom(typ
             Constructor<?> constructor = type.getConstructor(String.class);
             return constructor.newInstance(value);
         }
-        catch (Throwable ignored) {
+        catch (InvocationTargetException ex) {
+            throw new ParseOptionConversionException(name, value, type.getSimpleName(), ex.getTargetException());
+        }
+        catch (IllegalAccessException | IllegalArgumentException | InstantiationException | NoSuchMethodException | SecurityException ignored) {
```
Comment (findepi) [inline src/main/java/io/airlift/airline/TypeConverter.java]: Is there a reason to have `IllegalArgumentException` and `SecurityException` on the list?

File: src/main/java/io/airlift/airline/ParseOptionConversionException.java [hunk 2]
```diff
@@ -33,6 +33,14 @@
         this.typeName = typeName;
     }
 
+    ParseOptionConversionException(String optionTitle, String value, String typeName, Throwable cause)
+    {
```
Comment (findepi) [inline src/main/java/io/airlift/airline/ParseOptionConversionException.java]: Since the `cause` is nullable in exception classes' constructors, you can have the previous constructor delegate to the new. This would allow to avoid duplication of message formatting.

Comment (rtib) [reply src/main/java/io/airlift/airline/ParseOptionConversionException.java]: Absolutely correct. Fixed that.

**Comment by rtib** [comment]
As I see, the `valueOf` and `fromString` invocations may suffer the same problem, but I haven't tested them yet. I label this as Work-In-Progress for now and update it soon.

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 1 above)
Comment (rtib) [reply src/main/java/io/airlift/airline/TypeConverter.java]: Have used the IDE to replace catch the superclass with a multi-catch and than break the list up. But, indeed those two are irrelevant at that very point now.

Comment (findepi) [reply src/main/java/io/airlift/airline/TypeConverter.java]: thanks for clarifying. The remaining ones you can conveniently catch with `ReflectiveOperationException` (without `|`s)

Comment (rtib) [reply src/main/java/io/airlift/airline/TypeConverter.java]: I don't like this approach very much. I prefer a clear list of exceptions over catching the superclass. In this case, `InvocationTargetException` also extends the `ReflectiveOperationException`, which could be confusing. The implicit behavior would be correct, but it's cleaner to list them explicitly.

I will remove `IllegalArgumentException` and `SecurityException` from the list as they are unchecked anyway.

**Comment by rtib** [comment]
Had to struggle a bit with tests, but now it seems complete, squashed and ready for review.

File: src/main/java/io/airlift/airline/TypeConverter.java [hunk 3]
```diff
@@ -54,7 +55,11 @@ else if (Double.class.isAssignableFrom(type) || Double.TYPE.isAssignableFrom(typ
                 return valueOf.invoke(null, value);
             }
         }
-        catch (Throwable ignored) {
+        catch (InvocationTargetException ex) {
+            throw new ParseOptionConversionException(name, value, type.getSimpleName(), ex.getTargetException());
+        }
+        catch (IllegalAccessException |
+                NoSuchMethodException ignored) {
```
Comment (findepi) [inline src/main/java/io/airlift/airline/TypeConverter.java]: please wrap on previous line (same below)

File: src/test/java/io/airlift/airline/ArgConv.java [hunk 4]
```diff
@@ -0,0 +1,115 @@
+package io.airlift.airline;
+
+public class ArgConv {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/ArgConv.java]: We do not use abbreviations (except for certain well known).

Maybe `ArgumentConversion`?

Also, I'd put it as an inner class of the test class, but first we should clean the existing tests. So keep it separate for now.

File: src/test/java/io/airlift/airline/ArgConv.java [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+
+        @Override
+        public String toString() {
+            return value;
+        }
+        
+    }
+    
+    @Command(name = "const", description = "Test the argument class constructor")
+    public static class Const implements Runnable {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/ArgConv.java]: Constant or Constructor?

Rename to eg `ConstructorArgument`

File: src/test/java/io/airlift/airline/ArgConv.java [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+                .withDefaultCommand(Help.class)
+                .withCommand(Const.class)
+                .withCommand(ValueOf.class)
+                .withCommand(FromStr.class);
+        
+        Cli<Runnable> parser = builder.build();
+        parser.parse(args).run();
+    }
+    
+    public static class TestType1 {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/ArgConv.java]: Rename to eg `ConstructorArgument`

File: src/test/java/io/airlift/airline/ArgConv.java [hunk 7]
```diff
@@ -0,0 +1,115 @@
+package io.airlift.airline;
+
+public class ArgConv {
+
+    public static void main(String... args) {
+        Cli.CliBuilder<Runnable> builder = Cli.<Runnable>builder("argtest")
+                .withDescription("test the argument converter")
+                .withDefaultCommand(Help.class)
+                .withCommand(Const.class)
+                .withCommand(ValueOf.class)
```
Comment (findepi) [inline src/test/java/io/airlift/airline/ArgConv.java]: Do we need subcommands?
I think we could have just a bag of (optional) parameters and let a test method just set one argument.
like `"--value-of", "12345"`

This would reduce number of classes needed.

File: src/test/java/io/airlift/airline/TestArgConv.java [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+public class TestArgConv {
+    
+    @Test
+    public void testConstHappy() {
+        ArgConverter("const", "12345");
+    }
+    
+    @Test
+    public void testConstBad() {
+        Throwable catched = expectThrows(ParseOptionConversionException.class, () -> {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/TestArgConv.java]: Use `org.assertj.core.api.Assertions#assertThatThrownBy` from
```
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
```

File: src/test/java/io/airlift/airline/TestArgConv.java [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+            ArgConverter("const", "123456");
+        });
+        assertTrue(catched.getCause().getMessage().contains("(1) Argument too long."));
+    }
+    
+    @Test
+    public void testValueOfHappy() {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/TestArgConv.java]: s/Happy/Successful/  ie `testValueOfSuccessful`

 (same for others)

File: src/test/java/io/airlift/airline/TestArgConv.java [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+        ArgConverter("valueof", "12345");
+    }
+    
+    @Test
+    public void testValueOfBad() {
```
Comment (findepi) [inline src/test/java/io/airlift/airline/TestArgConv.java]: `testValueOfFailure`

**Comment by findepi** [comment]
@rtib i realized we don't have checkstyle enabled in airline yet.
I posted a PR (https://github.com/airlift/airline/pull/69). You may want to rebase on top.

File: src/test/java/io/airlift/airline/TestArgConv.java (hunk 8 above)
Comment (rtib) [reply src/test/java/io/airlift/airline/TestArgConv.java]: Need to assert the message of the cause. Don't know how to drill down to that with assertj.

Comment (rtib) [reply src/test/java/io/airlift/airline/TestArgConv.java]:
```
        assertThatThrownBy(() -> {
            ArgConverter("--value-of", "123456");
        }).isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("(2) Argument too long.");
```

this is failing, because its asserting the message of the `ParseOptionConversionException`, not its cause.

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 3 above)
Comment (dain) [reply src/main/java/io/airlift/airline/TypeConverter.java]: Instead if `IllegalAccessException | NoSuchMethodException` use just `ReflectiveOperationException`

File: src/main/java/io/airlift/airline/TypeConverter.java [hunk 11]
```diff
@@ -54,7 +55,11 @@ else if (Double.class.isAssignableFrom(type) || Double.TYPE.isAssignableFrom(typ
                 return valueOf.invoke(null, value);
             }
         }
-        catch (Throwable ignored) {
+        catch (InvocationTargetException ex) {
+            throw new ParseOptionConversionException(name, value, type.getSimpleName(), ex.getTargetException());
```
Comment (dain) [inline src/main/java/io/airlift/airline/TypeConverter.java]: Instead of immediately throwing, save off the exception for the end, and try the other techniques.  The existing code tries all techniques, and I think we want to maintain that behavior.

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 3 above)
Comment (rtib) [reply src/main/java/io/airlift/airline/TypeConverter.java]: We already had that discussed at https://github.com/airlift/airline/pull/68#discussion_r347261254

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 11 above)
Comment (rtib) [reply src/main/java/io/airlift/airline/TypeConverter.java]: I thought about that, however, `InvocationTargetException` is only throw if the target, i.e. `fromString` or `valueOf` or the constructor was found, invoked and has failed. Ignore and try another method is only advisable if the method was not found or could not be invoked.

**Comment by rtib** [comment]
rebased to #69

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 11 above)
Comment (dain) [reply src/main/java/io/airlift/airline/TypeConverter.java]: The problem is this code just guesses which methods to call.  It is possible that the class had different parsing techniques for each of these methods, and we don't know which one is "correct".  This is why we try all and only fail if nothing works.

File: src/test/java/io/airlift/airline/TestArgConv.java (hunk 8 above)
Comment (findepi) [reply src/test/java/io/airlift/airline/TestArgConv.java]: You can do something like:
```java
assertThatThrownBy(() -> ....)
        .isInstanceOf(...)
        .hasMessage("...")
        .satisfies(e -> assertThat(e.getCause())
                .isInstanceOf(...)
                .hasMessage("..."));
```

File: src/main/java/io/airlift/airline/TypeConverter.java (hunk 11 above)
Comment (findepi) [reply src/main/java/io/airlift/airline/TypeConverter.java]: @dain please see https://github.com/airlift/airlift/pull/759/commits/d6e67b8a794e622ec80dc02734a5caad26c159b0

File: src/main/java/io/airlift/airline/TypeConverter.java [hunk 12]
```diff
@@ -64,15 +68,23 @@ else if (Double.class.isAssignableFrom(type) || Double.TYPE.isAssignableFrom(typ
...
         try {
             Constructor<?> constructor = type.getConstructor(String.class);
             return constructor.newInstance(value);
         }
-        catch (Throwable ignored) {
+        catch (InvocationTargetException ex) {
+            throw new ParseOptionConversionException(name, value, type.getSimpleName(), ex.getTargetException());
+        }
+        catch (IllegalAccessException |
+                InstantiationException |
```
Comment (findepi) [inline src/main/java/io/airlift/airline/TypeConverter.java]: please put them all on one line

**Comment by findepi** [comment]
@rtib sorry for the delay. We had some internal discussion about https://github.com/airlift/airline/pull/68#discussion_r347576023

Can you please rebase & squash commits?
I'll do final pass then

**Comment by rtib** [comment]
Rebase to what base?

**Comment by findepi** [comment]
current master. the other PR is merged now.

**Comment by findepi** [comment]
Merged, thanks!

sorry for the delay, i didn't know you updated the PR

**Comment by findepi** [comment]
I just released airline 0.9.

@rtib thanks again for your contribution!
